<?php
// Deutsche Übersetzungsdatei
$translations = [
    // Navigation
    'home' => 'Startseite',
    'dashboard' => 'Dashboard',
    'create_order' => 'Bestellung erstellen',
    'login' => 'Anmelden', 
    'register' => 'Registrieren',
    'logout' => 'Abmelden',
    
    // Allgemeine Seiten
    'welcome' => 'Willkommen bei',
    'welcome_text' => 'Die einfache Lösung für die Organisation von Gruppenbestellungen.',
    'welcome_detail' => 'Erstellen Sie einfach Gruppenbestellungen, laden Sie Ihre Freunde ein und optimieren Sie die Versandkosten.',
    'please_login' => 'Melden Sie sich an oder registrieren Sie sich, um zu beginnen.',
    'register_now' => 'Registrieren',
    'login_now' => 'Anmelden',
    'create_order_now' => 'Bestellung erstellen',
    'my_dashboard' => 'Mein Dashboard',
    
    // Startseite-Abschnitte
    'create_orders' => 'Bestellungen erstellen',
    'create_orders_text' => 'Definieren Sie verfügbare Produkte, Fristen und Abholbedingungen.',
    'share_with_friends' => 'Mit Freunden teilen',
    'share_with_friends_text' => 'Laden Sie Teilnehmer einfach mit einem eindeutigen Link für jede Bestellung ein.',
    'save_on_fees' => 'Gebühren sparen',
    'save_on_fees_text' => 'Reduzieren Sie Versandkosten durch Gruppenbestellungen und teilen Sie sie fair auf.',
    'how_it_works' => 'Wie funktioniert es?',
    'step1' => 'Bestellung erstellen',
    'step1_text' => 'Definieren Sie Produkte, Termine und Versandkosten.',
    'step2' => 'Teilnehmer einladen',
    'step2_text' => 'Teilen Sie den eindeutigen Link Ihrer Bestellung.',
    'step3' => 'Bestellungen verfolgen',
    'step3_text' => 'Verwalten Sie Teilnehmer und deren Zahlungen.',
    'step4' => 'Verteilung organisieren',
    'step4_text' => 'Nehmen Sie Bestellungen entgegen und verteilen Sie sie.',
    
    // Benutzerkonto
    'first_name' => 'Vorname',
    'last_name' => 'Nachname',
    'email' => 'E-Mail',
    'password' => 'Passwort',
    'confirm_password' => 'Passwort bestätigen',
    'already_registered' => 'Bereits registriert?',
    'not_registered' => 'Noch kein Konto?',
    'sign_up' => 'Registrieren',
    
    // Dashboards
    'orders_created' => 'Erstellte Bestellungen',
    'orders_joined' => 'Teilgenommene Bestellungen',
    'orders_completed' => 'Abgeschlossene Bestellungen',
    'my_created_orders' => 'Meine erstellten Bestellungen',
    'my_participations' => 'Meine Teilnahmen',
    'no_orders_created' => 'Sie haben noch keine Bestellungen erstellt.',
    'create_one_now' => 'Jetzt eine erstellen',
    'no_participations' => 'Sie nehmen derzeit an keinen Bestellungen teil.',
    
    // Bestellung
    'order' => 'Bestellung',
    'order_title' => 'Bestelltitel',
    'order_type' => 'Bestelltyp',
    'deadline' => 'Frist',
    'pickup_date' => 'Abholdatum',
    'pickup_address' => 'Abholadresse',
    'weight_based' => 'Basierend auf Gesamtgewicht',
    'quantity_based' => 'Basierend auf Artikelanzahl',
    'amount_based' => 'Basierend auf Gesamtkosten',
    'tiers' => 'Versandstaffeln',
    'product_name' => 'Produktname',
    'product_url' => 'Informations-URL (optional)',
    'product_url_help' => 'Link zur Produktinformationsseite',
    'product_variation' => 'Variation',
    'product_weight' => 'Gewicht',
    'product_price' => 'Preis',
    'product_quantity' => 'Menge',
    'add_product' => 'Produkt hinzufügen',
    'add_variation' => 'Variation hinzufügen',
    'variation_name' => 'Variationsname',
    'min' => 'Min',
    'max' => 'Max',
    'shipping_cost' => 'Kosten (€)',
    'add_tier' => 'Staffel hinzufügen',
    'create_order_btn' => 'Bestellung erstellen',
    'cancel' => 'Abbrechen',
    'add' => 'Hinzufügen',
    'remove' => 'Entfernen',
    'more_info' => 'Weitere Informationen',
    
    // Bestellstatus
    'open' => 'Offen',
    'closed' => 'Geschlossen',
    'created_on' => 'Erstellt am',
    'manage' => 'Verwalten',
    'view' => 'Ansehen',
    'view_edit' => 'Ansehen / Bearbeiten',
    
    // Admin-Bestellverwaltung
    'information' => 'Informationen',
    'statistics' => 'Statistiken',
    'participants' => 'Teilnehmer',
    'products' => 'Produkte',
    'admin_mode' => 'Admin-Modus',
    'back_to_dashboard' => 'Zurück zum Dashboard',
    'share_link' => 'Link teilen',
    'copy' => 'Kopieren',
    'send_reminder' => 'Erinnerung senden',
    'send_pickup_info' => 'Abholinformationen senden',
    'total_amount' => 'Gesamtbetrag',
    'shipping_fee' => 'Versandkosten',
    'current_tier' => 'Aktuelle Stufe',
    'next_tier' => 'noch {weight} kg zur nächsten Stufe',
    'payments' => 'Zahlungen',
    'received' => 'erhalten von',
    'total_weight' => 'Gesamtgewicht',
    'available_products' => 'Verfügbare Produkte',
    'no_products_yet' => 'Dieser Bestellung wurden noch keine Produkte hinzugefügt.',
    'update_order' => 'Meine Bestellung aktualisieren',
    
    // Teilnehmer
    'organizer' => 'Organisator',
    'must_login' => 'Sie müssen angemeldet sein, um an dieser Bestellung teilzunehmen.',
    'join_order' => 'An dieser Bestellung teilnehmen',
    'my_order' => 'Meine Bestellung',
    'total_to_pay' => 'Zu zahlender Betrag',
    'payment_status' => 'Zahlungsstatus',
    'paid' => 'Bezahlt',
    'unpaid' => 'Unbezahlt',
    'mark_as_paid' => 'Als bezahlt markieren',
    'mark_as_unpaid' => 'Als unbezahlt markieren',
    'order_summary' => 'Bestellübersicht',
    'summary_total' => 'GESAMT',
    'grand_total' => 'GESAMTSUMME',
    
    // Nachrichten
    'error_occurred' => 'Ein Fehler ist aufgetreten.',
    'order_created' => 'Bestellung erfolgreich erstellt.',
    'order_updated' => 'Ihre Bestellung wurde erfolgreich aktualisiert.',
    'product_added' => 'Produkt erfolgreich hinzugefügt.',
    'reminder_sent' => 'Erinnerung erfolgreich gesendet.',
    'pickup_info_sent' => 'Abholinformationen erfolgreich gesendet.',
    'payment_updated' => 'Zahlungsstatus aktualisiert.',
    'joined_order' => 'Sie haben erfolgreich an der Bestellung teilgenommen.',
    'account_created' => 'Ihr Konto wurde erfolgreich erstellt.',
    'logged_out' => 'Sie wurden abgemeldet.',
    'login_success' => 'Anmeldung erfolgreich.',
    'must_login_to_join' => 'Sie müssen angemeldet sein, um an dieser Bestellung teilzunehmen.',
    'order_closed' => 'Diese Bestellung ist geschlossen. Sie können sie nicht mehr ändern.',
    
    // Validierung
    'required_field' => 'Dieses Feld ist erforderlich.',
    'invalid_email' => 'E-Mail ist nicht gültig.',
    'email_exists' => 'Diese E-Mail wird bereits verwendet.',
    'min_8_chars' => 'Mindestens 8 Zeichen.',
    'passwords_not_match' => 'Passwörter stimmen nicht überein.',
    'invalid_date' => 'Ungültiges Datumsformat.',
    'future_date' => 'Das Datum muss in der Zukunft liegen.',
    'pickup_after_deadline' => 'Abholdatum muss nach der Frist liegen.',
    'at_least_one_tier' => 'Mindestens eine Versandstaffel ist erforderlich.',
    'invalid_url' => 'Produkt-URL ist nicht gültig.',
    'at_least_one_variation' => 'Mindestens eine gültige Variation ist erforderlich.',
    'wrong_credentials' => 'Falsche E-Mail oder falsches Passwort.',
];
?>