<?php
// English translation file
$translations = [
    // Navigation
    'home' => 'Home',
    'dashboard' => 'Dashboard',
    'create_order' => 'Create an Order',
    'login' => 'Login', 
    'register' => 'Register',
    'logout' => 'Logout',
    
    // General pages
    'welcome' => 'Welcome to',
    'welcome_text' => 'The simple solution for organizing group orders.',
    'welcome_detail' => 'Easily create group orders, invite your friends, and optimize shipping costs.',
    'please_login' => 'Sign up or log in to get started.',
    'register_now' => 'Sign Up',
    'login_now' => 'Log In',
    'create_order_now' => 'Create an Order',
    'my_dashboard' => 'My Dashboard',
    
    // Home sections
    'create_orders' => 'Create Orders',
    'create_orders_text' => 'Define available products, deadlines, and pickup conditions.',
    'share_with_friends' => 'Share with Friends',
    'share_with_friends_text' => 'Easily invite participants with a unique link for each order.',
    'save_on_fees' => 'Save on Fees',
    'save_on_fees_text' => 'Reduce shipping costs through group orders and split them fairly.',
    'how_it_works' => 'How it Works?',
    'step1' => 'Create an Order',
    'step1_text' => 'Define products, dates, and shipping costs.',
    'step2' => 'Invite Participants',
    'step2_text' => 'Share your order\'s unique link.',
    'step3' => 'Track Orders',
    'step3_text' => 'Manage participants and their payments.',
    'step4' => 'Organize Distribution',
    'step4_text' => 'Receive orders and distribute them.',
    
    // User account
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'already_registered' => 'Already registered?',
    'not_registered' => 'Don\'t have an account?',
    'sign_up' => 'Sign Up',
    
    // Dashboards
    'orders_created' => 'Orders Created',
    'orders_joined' => 'Orders Joined',
    'orders_completed' => 'Orders Completed',
    'my_created_orders' => 'My Created Orders',
    'my_participations' => 'My Participations',
    'no_orders_created' => 'You haven\'t created any orders yet.',
    'create_one_now' => 'Create one now',
    'no_participations' => 'You are not participating in any orders at the moment.',
    
    // Order
    'order' => 'Order',
    'order_title' => 'Order Title',
    'order_type' => 'Order Type',
    'deadline' => 'Deadline',
    'pickup_date' => 'Pickup Date',
    'pickup_address' => 'Pickup Address',
    'weight_based' => 'Based on total weight',
    'quantity_based' => 'Based on number of items',
    'amount_based' => 'Based on total cost',
    'tiers' => 'Shipping Tiers',
    'product_name' => 'Product Name',
    'product_url' => 'Information URL (optional)',
    'product_url_help' => 'Link to product information page',
    'product_variation' => 'Variation',
    'product_weight' => 'Weight',
    'product_price' => 'Price',
    'product_quantity' => 'Quantity',
    'add_product' => 'Add Product',
    'add_variation' => 'Add Variation',
    'variation_name' => 'Variation Name',
    'min' => 'Min',
    'max' => 'Max',
    'shipping_cost' => 'Cost (€)',
    'add_tier' => 'Add Tier',
    'create_order_btn' => 'Create Order',
    'cancel' => 'Cancel',
    'add' => 'Add',
    'remove' => 'Remove',
    'more_info' => 'More information',
    
    // Order status
    'open' => 'Open',
    'closed' => 'Closed',
    'created_on' => 'Created on',
    'manage' => 'Manage',
    'view' => 'View',
    'view_edit' => 'View / Edit',
    
    // Admin order management
    'information' => 'Information',
    'statistics' => 'Statistics',
    'participants' => 'Participants',
    'products' => 'Products',
    'admin_mode' => 'Admin Mode',
    'back_to_dashboard' => 'Back to Dashboard',
    'share_link' => 'Share Link',
    'copy' => 'Copy',
    'send_reminder' => 'Send Reminder',
    'send_pickup_info' => 'Send Pickup Info',
    'total_amount' => 'Total Amount',
    'shipping_fee' => 'Shipping Fee',
    'current_tier' => 'Current tier',
    'next_tier' => 'another {weight} kg to next tier',
    'payments' => 'Payments',
    'received' => 'received of',
    'total_weight' => 'Total Weight',
    'available_products' => 'Available Products',
    'no_products_yet' => 'No products have been added to this order yet.',
    'update_order' => 'Update My Order',
    
    // Participant
    'organizer' => 'Organizer',
    'must_login' => 'You must be logged in to join this order.',
    'join_order' => 'Join this Order',
    'my_order' => 'My Order',
    'total_to_pay' => 'Total to Pay',
    'payment_status' => 'Payment Status',
    'paid' => 'Paid',
    'unpaid' => 'Unpaid',
    'mark_as_paid' => 'Mark as Paid',
    'mark_as_unpaid' => 'Mark as Unpaid',
    'order_summary' => 'Order Summary',
    'summary_total' => 'TOTAL',
    'grand_total' => 'GRAND TOTAL',
    
    // Messages
    'error_occurred' => 'An error occurred.',
    'order_created' => 'Order created successfully.',
    'order_updated' => 'Your order has been updated successfully.',
    'product_added' => 'Product added successfully.',
    'reminder_sent' => 'Reminder sent successfully.',
    'pickup_info_sent' => 'Pickup information sent successfully.',
    'payment_updated' => 'Payment status updated.',
    'joined_order' => 'You have successfully joined the order.',
    'account_created' => 'Your account has been created successfully.',
    'logged_out' => 'You have been logged out.',
    'login_success' => 'Login successful.',
    'must_login_to_join' => 'You must be logged in to join this order.',
    'order_closed' => 'This order is closed. You can no longer modify it.',
    
    // Validation
    'required_field' => 'This field is required.',
    'invalid_email' => 'Email is not valid.',
    'email_exists' => 'This email is already in use.',
    'min_8_chars' => '8 characters minimum.',
    'passwords_not_match' => 'Passwords do not match.',
    'invalid_date' => 'Invalid date format.',
    'future_date' => 'The date must be in the future.',
    'pickup_after_deadline' => 'Pickup date must be after the deadline.',
    'at_least_one_tier' => 'At least one shipping tier is required.',
    'invalid_url' => 'Product URL is not valid.',
    'at_least_one_variation' => 'At least one valid variation is required.',
    'wrong_credentials' => 'Incorrect email or password.',
];
?>