<?php
// English translation file
$translations = [
    // Navigation
    'home' => 'Home',
    'dashboard' => 'Dashboard',
    'create_order' => 'Create an Order',
    'login' => 'Login', 
    'register' => 'Register',
    'logout' => 'Logout',
    
    // General pages
    'welcome' => 'Welcome to',
    'welcome_text' => 'The simple solution for organizing group orders.',
    'welcome_detail' => 'Easily create group orders, invite your friends, and optimize shipping costs.',
    'please_login' => 'Sign up or log in to get started.',
    'register_now' => 'Sign Up',
    'login_now' => 'Log In',
    'create_order_now' => 'Create an Order',
    'my_dashboard' => 'My Dashboard',
    
    // Home sections
    'create_orders' => 'Create Orders',
    'create_orders_text' => 'Define available products, deadlines, and pickup conditions.',
    'share_with_friends' => 'Share with Friends',
    'share_with_friends_text' => 'Easily invite participants with a unique link for each order.',
    'save_on_fees' => 'Save on Fees',
    'save_on_fees_text' => 'Reduce shipping costs through group orders and split them fairly.',
    'how_it_works' => 'How it Works?',
    'step1' => 'Create an Order',
    'step1_text' => 'Define products, dates, and shipping costs.',
    'step2' => 'Invite Participants',
    'step2_text' => 'Share your order\'s unique link.',
    'step3' => 'Track Orders',
    'step3_text' => 'Manage participants and their payments.',
    'step4' => 'Organize Distribution',
    'step4_text' => 'Receive orders and distribute them.',
    
    // User account
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'email' => 'Email',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'already_registered' => 'Already registered?',
    'not_registered' => 'Don\'t have an account?',
    'sign_up' => 'Sign Up',
    
    // Dashboards
    'orders_created' => 'Orders Created',
    'orders_joined' => 'Orders Joined',
    'orders_completed' => 'Orders Completed',
    'my_created_orders' => 'My Created Orders',
    'my_participations' => 'My Participations',
    'no_orders_created' => 'You haven\'t created any orders yet.',
    'create_one_now' => 'Create one now',
    'no_participations' => 'You are not participating in any orders at the moment.',
    'public_orders' => 'Public Orders',
    'import_order' => 'Import an Order',
    
    // Order
    'order' => 'Order',
    'order_title' => 'Order Title',
    'order_type' => 'Order Type',
    'deadline' => 'Deadline',
    'pickup_date' => 'Pickup Date',
    'pickup_address' => 'Pickup Address',
    'weight_based' => 'Based on total weight',
    'quantity_based' => 'Based on number of items',
    'amount_based' => 'Based on total cost',
    'tiers' => 'Shipping Tiers',
    'product_name' => 'Product Name',
    'product_url' => 'Information URL (optional)',
    'product_url_help' => 'Link to product information page',
    'product_variation' => 'Variation',
    'product_weight' => 'Weight',
    'product_price' => 'Price',
    'product_quantity' => 'Quantity',
    'add_product' => 'Add Product',
    'add_variation' => 'Add Variation',
    'variation_name' => 'Variation Name',
    'min' => 'Min',
    'max' => 'Max',
    'shipping_cost' => 'Cost (€)',
    'add_tier' => 'Add Tier',
    'shipping_tiers' => 'Shipping tiers',
    'no_shipping_tiers' => 'No tiers defined',
    'create_order_btn' => 'Create Order',
    'cancel' => 'Cancel',
    'add' => 'Add',
    'remove' => 'Remove',
    'more_info' => 'More information',
    
    // Order status
    'open' => 'Open',
    'closed' => 'Closed',
    'created_on' => 'Created on',
    'manage' => 'Manage',
    'view' => 'View',
    'view_edit' => 'View / Edit',
    
    // Admin order management
    'information' => 'Information',
    'statistics' => 'Statistics',
    'participants' => 'Participants',
    'products' => 'Products',
    'admin_mode' => 'Admin Mode',
    'back_to_dashboard' => 'Back to Dashboard',
    'share_link' => 'Share Link',
    'copy' => 'Copy',
    'send_reminder' => 'Send Reminder',
    'send_pickup_info' => 'Send Pickup Info',
    'total_amount' => 'Total Amount',
    'shipping_fee' => 'Shipping Fee',
    'current_tier' => 'Current tier',
    'next_tier' => 'another {weight} kg to next tier',
    'payments' => 'Payments',
    'received' => 'received of',
    'total_weight' => 'Total Weight',
    'available_products' => 'Available Products',
    'no_products_yet' => 'No products have been added to this order yet.',
    'update_order' => 'Update My Order',
    
    // Participant
    'organizer' => 'Organizer',
    'must_login' => 'You must be logged in to join this order.',
    'join_order' => 'Join this Order',
    'my_order' => 'My Order',
    'total_to_pay' => 'Total to Pay',
    'payment_status' => 'Payment Status',
    'paid' => 'Paid',
    'unpaid' => 'Unpaid',
    'mark_as_paid' => 'Mark as Paid',
    'mark_as_unpaid' => 'Mark as Unpaid',
    'order_summary' => 'Order Summary',
    'summary_total' => 'TOTAL',
    'grand_total' => 'GRAND TOTAL',
    
    // Messages
    'error_occurred' => 'An error occurred.',
    'order_created' => 'Order created successfully.',
    'order_updated' => 'Your order has been updated successfully.',
    'product_added' => 'Product added successfully.',
    'reminder_sent' => 'Reminder sent successfully.',
    'pickup_info_sent' => 'Pickup information sent successfully.',
    'payment_updated' => 'Payment status updated.',
    'joined_order' => 'You have successfully joined the order.',
    'account_created' => 'Your account has been created successfully.',
    'logged_out' => 'You have been logged out.',
    'login_success' => 'Login successful.',
    'must_login_to_join' => 'You must be logged in to join this order.',
    'order_closed' => 'This order is closed. You can no longer modify it.',
    'turnstile_failed' => 'Robot verification failed. Please try again.',
    
    // Validation
    'required_field' => 'This field is required.',
    'invalid_email' => 'Email is not valid.',
    'email_exists' => 'This email is already in use.',
    'min_8_chars' => '8 characters minimum.',
    'passwords_not_match' => 'Passwords do not match.',
    'invalid_date' => 'Invalid date format.',
    'future_date' => 'The date must be in the future.',
    'pickup_after_deadline' => 'Pickup date must be after the deadline.',
    'at_least_one_tier' => 'At least one shipping tier is required.',
    'invalid_url' => 'Product URL is not valid.',
    'at_least_one_variation' => 'At least one valid variation is required.',
    'wrong_credentials' => 'Incorrect email or password.',
    'invalid_order_type' => 'Invalid order type.',
    
    // New keys for commande.php
    'missing_order_id' => 'Missing order ID.',
    'order_not_found' => 'Order not found.',
    'administrator' => 'Administrator',
    'description' => 'Description',
    'product' => 'Product',
    'weight' => 'Weight',
    'price' => 'Price',
    'quantity' => 'Quantity',
    'info' => 'Info',
    'update_my_order' => 'Update my order',
    'variation' => 'Variation',
    'amount' => 'Amount',
    'total' => 'TOTAL',
    'shipping_fees' => 'Shipping fees',
    'no_products_added' => 'No products have been added to this order yet.',
    
    // New keys for import_commande.php
    'must_login_to_import' => 'You must be logged in to import an order.',
    'file_upload_error' => 'Error uploading file.',
    'file_read_error' => 'Unable to read file content.',
    'order_imported' => 'Order imported successfully.',
    'import_from_file' => 'Import from file',
    'import' => 'Import',
    'import_from_text' => 'Import from text',
    
    // Admin order page
    'manage_order' => 'Order Management',
    'view_order' => 'View Order',
    'back_to_dashboard' => 'Back to Dashboard',
    'information' => 'Information',
    'deadline' => 'Deadline',
    'modify' => 'Modify',
    'pickup' => 'Pickup',
    'order_type' => 'Order Type',
    'weight_based' => 'Weight-based',
    'quantity_based' => 'Quantity-based',
    'amount_based' => 'Amount-based',
    'share_link' => 'Share Link',
    'copy' => 'Copy',
    'description' => 'Description',
    'add' => 'Add',
    'visibility' => 'Visibility',
    'make_private' => 'Make Private',
    'make_public' => 'Make Public',
    'public_order_info' => 'This order is visible to all users on the dashboard.',
    'private_order_info' => 'This order is only visible to participants.',
    'send_reminder' => 'Send Reminder',
    'send_pickup_info' => 'Send Pickup Info',
    'export_pdf' => 'Export to PDF',
    'duplicate' => 'Duplicate',
    'statistics' => 'Statistics',
    'participants' => 'Participants',
    'products' => 'Products',
    'total_amount' => 'Total Amount',
    'shipping_cost' => 'Shipping Cost',
    'total_weight' => 'Total Weight',
    'current_tier' => 'Current tier',
    'next_tier_info' => '{weight} kg more for next tier',
    'payments' => 'Payments',
    'received' => 'received out of',
    'add_product' => 'Add Product',
    'no_products' => 'No products have been added to this order.',
    'product_info' => 'Info',
    'delete_product_confirm' => 'Are you sure you want to delete this product?',
    'variation' => 'Variation',
    'weight' => 'Weight',
    'price' => 'Price',
    'actions' => 'Actions',
    'delete_variation_confirm' => 'Are you sure you want to delete this variation?',
    'no_participants' => 'No participants have joined this order.',
    'participant' => 'Participant',
    'product_amount' => 'Product Amount',
    'shipping_share' => 'Shipping Share',
    'total' => 'Total',
    'payment_status' => 'Payment Status',
    'paid' => 'Paid',
    'unpaid' => 'Unpaid',
    'mark_as_paid' => 'Mark as Paid',
    'mark_as_unpaid' => 'Mark as Unpaid',
    'product_name' => 'Product Name',
    'product_url' => 'Information URL (optional)',
    'product_url_help' => 'Link to a product information page',
    'variations' => 'Variations',
    'variation_name' => 'Variation Name',
    'product_weight' => 'Weight (kg)',
    'product_price' => 'Price (€)',
    'remove' => 'Remove',
    'add_variation' => 'Add Variation',
    'cancel' => 'Cancel',
    'update_dates' => 'Update Dates',
    'deadline_help' => 'Deadline for placing orders',
    'pickup_date' => 'Pickup Date',
    'pickup_help' => 'Date for picking up products',
    'update' => 'Update',
    'order_description' => 'Order Description',
    'order_description_placeholder' => 'Describe your group order, special conditions, etc.',
    'order_description_help' => 'This description will be visible to all participants of the order.',
    'description_help' => 'Additional information about the order',
    'save' => 'Save',
    'link_copied' => 'Link copied to clipboard!',
    'no_products_participant' => 'No products',
    'created_on' => 'Created on',
    'organizer' => 'Organizer',
    
    // New keys
    'product_info_url' => 'Information URL (optional)',
    'product_info_url_description' => 'Link to product information page',
    'based_on_weight' => 'Based on total weight',
    'based_on_quantity' => 'Based on number of items',
    'based_on_amount' => 'Based on total amount',
    'private_order_description' => 'This order is only visible to participants',
    'send_pickup' => 'Send pickup information',
    'duplicate_order' => 'Duplicate order',
    'paid_amount' => 'Amount received',
    'received_from' => 'from a total of',
    'pdf_generated_successfully' => 'PDF generated successfully',
    'error_generating_pdf' => 'Error generating PDF',
    'tcpdf_not_available' => 'TCPDF is not installed. PDF export is not available.',
    
    // Export/Import JSON
    'export_json' => 'Export JSON',
    'import_order' => 'Import Order',
    'import_json_file' => 'Import JSON File',
    'select_json_file' => 'Select JSON File',
    'json_file_format_info' => 'Accepted format: .json files exported from Groupon',
    'import_file' => 'Import File',
    'import_info' => 'Import Information',
    'supported_format' => 'Supported Format',
    'json_format_description' => 'Only JSON files exported from Groupon are accepted.',
    'import_notes' => 'Important Notes',
    'import_note_1' => 'A new ID will be generated for the order',
    'import_note_2' => 'Only existing participants will be imported',
    'import_note_3' => 'You will become the administrator of the imported order',
    'create_new_order' => 'Create New Order',
    'import_success' => 'Order imported successfully!',
    'import_error' => 'Error importing order',
    'import_error_read_file' => 'Error reading file',
    'import_error_upload' => 'Error uploading file',
    'view_order' => 'View Order',
];
?>