<?php
// Archivo de traducción español
$translations = [
    // Navegación
    'home' => 'Inicio',
    'dashboard' => 'Panel de control',
    'create_order' => 'Crear pedido',
    'login' => 'Iniciar sesión', 
    'register' => 'Registrarse',
    'logout' => 'Cerrar sesión',
    
    // Páginas generales
    'welcome' => 'Bienvenido a',
    'welcome_text' => 'La solución simple para organizar pedidos en grupo.',
    'welcome_detail' => 'Crea fácilmente pedidos en grupo, invita a tus amigos y optimiza los gastos de envío.',
    'please_login' => 'Regístrate o inicia sesión para comenzar.',
    'register_now' => 'Registrarse',
    'login_now' => 'Iniciar sesión',
    'create_order_now' => 'Crear un pedido',
    'my_dashboard' => 'Mi panel de control',
    
    // Secciones de inicio
    'create_orders' => 'Crea pedidos',
    'create_orders_text' => 'Define productos disponibles, fechas límite y condiciones de recogida.',
    'share_with_friends' => 'Comparte con amigos',
    'share_with_friends_text' => 'Invita fácilmente a participantes con un enlace único para cada pedido.',
    'save_on_fees' => 'Ahorra en tarifas',
    'save_on_fees_text' => 'Reduce los gastos de envío a través de pedidos en grupo y divídelos equitativamente.',
    'how_it_works' => '¿Cómo funciona?',
    'step1' => 'Crea un pedido',
    'step1_text' => 'Define productos, fechas y gastos de envío.',
    'step2' => 'Invita a participantes',
    'step2_text' => 'Comparte el enlace único de tu pedido.',
    'step3' => 'Sigue los pedidos',
    'step3_text' => 'Gestiona participantes y sus pagos.',
    'step4' => 'Organiza la distribución',
    'step4_text' => 'Recibe pedidos y distribúyelos.',
    
    // Cuenta de usuario
    'first_name' => 'Nombre',
    'last_name' => 'Apellido',
    'email' => 'Correo electrónico',
    'password' => 'Contraseña',
    'confirm_password' => 'Confirmar contraseña',
    'already_registered' => '¿Ya registrado?',
    'not_registered' => '¿No tienes cuenta?',
    'sign_up' => 'Registrarse',
    
    // Paneles de control
    'orders_created' => 'Pedidos creados',
    'orders_joined' => 'Pedidos unidos',
    'orders_completed' => 'Pedidos completados',
    'my_created_orders' => 'Mis pedidos creados',
    'my_participations' => 'Mis participaciones',
    'no_orders_created' => 'Aún no has creado ningún pedido.',
    'create_one_now' => 'Crear uno ahora',
    'no_participations' => 'No estás participando en ningún pedido actualmente.',
    
    // Pedido
    'order' => 'Pedido',
    'order_title' => 'Título del pedido',
    'order_type' => 'Tipo de pedido',
    'deadline' => 'Fecha límite',
    'pickup_date' => 'Fecha de recogida',
    'pickup_address' => 'Dirección de recogida',
    'weight_based' => 'Basado en peso total',
    'quantity_based' => 'Basado en número de artículos',
    'amount_based' => 'Basado en costo total',
    'tiers' => 'Niveles de envío',
    'product_name' => 'Nombre del producto',
    'product_url' => 'URL de información (opcional)',
    'product_url_help' => 'Enlace a página de información del producto',
    'product_variation' => 'Variación',
    'product_weight' => 'Peso',
    'product_price' => 'Precio',
    'product_quantity' => 'Cantidad',
    'add_product' => 'Añadir producto',
    'add_variation' => 'Añadir variación',
    'variation_name' => 'Nombre de variación',
    'min' => 'Mín',
    'max' => 'Máx',
    'shipping_cost' => 'Costo (€)',
    'add_tier' => 'Añadir nivel',
    'create_order_btn' => 'Crear pedido',
    'cancel' => 'Cancelar',
    'add' => 'Añadir',
    'remove' => 'Eliminar',
    'more_info' => 'Más información',
    
    // Estado del pedido
    'open' => 'Abierto',
    'closed' => 'Cerrado',
    'created_on' => 'Creado el',
    'manage' => 'Gestionar',
    'view' => 'Ver',
    'view_edit' => 'Ver / Editar',
    
    // Gestión de pedido admin
    'information' => 'Información',
    'statistics' => 'Estadísticas',
    'participants' => 'Participantes',
    'products' => 'Productos',
    'admin_mode' => 'Modo administrador',
    'back_to_dashboard' => 'Volver al panel',
    'share_link' => 'Compartir enlace',
    'copy' => 'Copiar',
    'send_reminder' => 'Enviar recordatorio',
    'send_pickup_info' => 'Enviar info de recogida',
    'total_amount' => 'Importe total',
    'shipping_fee' => 'Gastos de envío',
    'current_tier' => 'Nivel actual',
    'next_tier' => 'otros {weight} kg para el siguiente nivel',
    'payments' => 'Pagos',
    'received' => 'recibidos de',
    'total_weight' => 'Peso total',
    'available_products' => 'Productos disponibles',
    'no_products_yet' => 'Aún no se han añadido productos a este pedido.',
    'update_order' => 'Actualizar mi pedido',
    
    // Participante
    'organizer' => 'Organizador',
    'must_login' => 'Debes iniciar sesión para unirte a este pedido.',
    'join_order' => 'Unirse a este pedido',
    'my_order' => 'Mi pedido',
    'total_to_pay' => 'Total a pagar',
    'payment_status' => 'Estado de pago',
    'paid' => 'Pagado',
    'unpaid' => 'No pagado',
    'mark_as_paid' => 'Marcar como pagado',
    'mark_as_unpaid' => 'Marcar como no pagado',
    'order_summary' => 'Resumen del pedido',
    'summary_total' => 'TOTAL',
    'grand_total' => 'TOTAL GENERAL',
    
    // Mensajes
    'error_occurred' => 'Ha ocurrido un error.',
    'order_created' => 'Pedido creado con éxito.',
    'order_updated' => 'Tu pedido ha sido actualizado con éxito.',
    'product_added' => 'Producto añadido con éxito.',
    'reminder_sent' => 'Recordatorio enviado con éxito.',
    'pickup_info_sent' => 'Información de recogida enviada con éxito.',
    'payment_updated' => 'Estado de pago actualizado.',
    'joined_order' => 'Te has unido al pedido con éxito.',
    'account_created' => 'Tu cuenta ha sido creada con éxito.',
    'logged_out' => 'Has cerrado sesión.',
    'login_success' => 'Inicio de sesión exitoso.',
    'must_login_to_join' => 'Debes iniciar sesión para unirte a este pedido.',
    'order_closed' => 'Este pedido está cerrado. Ya no puedes modificarlo.',
    
    // Validación
    'required_field' => 'Este campo es obligatorio.',
    'invalid_email' => 'El correo electrónico no es válido.',
    'email_exists' => 'Este correo electrónico ya está en uso.',
    'min_8_chars' => 'Mínimo 8 caracteres.',
    'passwords_not_match' => 'Las contraseñas no coinciden.',
    'invalid_date' => 'Formato de fecha no válido.',
    'future_date' => 'La fecha debe estar en el futuro.',
    'pickup_after_deadline' => 'La fecha de recogida debe ser posterior a la fecha límite.',
    'at_least_one_tier' => 'Se requiere al menos un nivel de envío.',
    'invalid_url' => 'La URL del producto no es válida.',
    'at_least_one_variation' => 'Se requiere al menos una variación válida.',
    'wrong_credentials' => 'Correo electrónico o contraseña incorrectos.',
];
?>