<?php
// Fichier de traduction français
$translations = [
    // Navigation
    'home' => 'Accueil',
    'dashboard' => 'Tableau de bord',
    'create_order' => 'Créer une commande',
    'login' => 'Connexion', 
    'register' => 'Inscription',
    'logout' => 'Déconnexion',
    
    // Pages générales
    'welcome' => 'Bienvenue sur',
    'welcome_text' => 'La solution simple pour organiser vos commandes groupées.',
    'welcome_detail' => 'Créez facilement des commandes groupées, invitez vos amis, et optimisez les frais de livraison.',
    'please_login' => 'Inscrivez-vous ou connectez-vous pour commencer.',
    'register_now' => 'S\'inscrire',
    'login_now' => 'Se connecter',
    'create_order_now' => 'Créer une commande',
    'my_dashboard' => 'Mon tableau de bord',
    
    // Sections accueil
    'create_orders' => 'Créez des commandes',
    'create_orders_text' => 'Définissez les produits disponibles, les dates limites et les conditions de récupération.',
    'share_with_friends' => 'Partagez avec vos amis',
    'share_with_friends_text' => 'Invitez facilement des participants grâce à un lien unique pour chaque commande.',
    'save_on_fees' => 'Économisez sur les frais',
    'save_on_fees_text' => 'Réduisez les frais de port grâce aux commandes groupées et répartissez-les équitablement.',
    'how_it_works' => 'Comment ça marche ?',
    'step1' => 'Créez une commande',
    'step1_text' => 'Définissez les produits, les dates et les frais de port.',
    'step2' => 'Invitez des participants',
    'step2_text' => 'Partagez le lien unique de votre commande.',
    'step3' => 'Suivez les commandes',
    'step3_text' => 'Gérez les participants et leurs paiements.',
    'step4' => 'Organisez la distribution',
    'step4_text' => 'Récupérez les commandes et distribuez-les.',
    
    // Compte utilisateur
    'first_name' => 'Prénom',
    'last_name' => 'Nom',
    'email' => 'Email',
    'password' => 'Mot de passe',
    'confirm_password' => 'Confirmation du mot de passe',
    'already_registered' => 'Déjà inscrit ?',
    'not_registered' => 'Pas encore de compte ?',
    'sign_up' => 'S\'inscrire',
    
    // Tableaux de bord
    'orders_created' => 'Commandes créées',
    'orders_joined' => 'Commandes participées',
    'orders_completed' => 'Commandes terminées',
    'my_created_orders' => 'Mes commandes créées',
    'my_participations' => 'Mes participations',
    'no_orders_created' => 'Vous n\'avez pas encore créé de commande.',
    'create_one_now' => 'Créez-en une maintenant',
    'no_participations' => 'Vous ne participez à aucune commande pour le moment.',
    
    // Commande
    'order' => 'Commande',
    'order_title' => 'Titre de la commande',
    'order_type' => 'Type de commande',
    'deadline' => 'Date limite',
    'pickup_date' => 'Date de récupération',
    'pickup_address' => 'Adresse de récupération',
    'weight_based' => 'Basée sur le poids total',
    'quantity_based' => 'Basée sur le nombre de produits',
    'amount_based' => 'Basée sur le coût total',
    'tiers' => 'Paliers de frais de port',
    'product_name' => 'Nom du produit',
    'product_url' => 'URL d\'information (facultatif)',
    'product_url_help' => 'Lien vers une page d\'information sur le produit',
    'product_variation' => 'Variation',
    'product_weight' => 'Poids',
    'product_price' => 'Prix',
    'product_quantity' => 'Quantité',
    'add_product' => 'Ajouter un produit',
    'add_variation' => 'Ajouter une variation',
    'variation_name' => 'Nom de la variation',
    'min' => 'Min',
    'max' => 'Max',
    'shipping_cost' => 'Frais (€)',
    'add_tier' => 'Ajouter un palier',
    'create_order_btn' => 'Créer la commande',
    'cancel' => 'Annuler',
    'add' => 'Ajouter',
    'remove' => 'Supprimer',
    'more_info' => 'Plus d\'informations',
    
    // État des commandes
    'open' => 'Ouverte',
    'closed' => 'Fermée',
    'created_on' => 'Créée le',
    'manage' => 'Gérer',
    'view' => 'Voir',
    'view_edit' => 'Voir / Modifier',
    
    // Gestion commande admin
    'information' => 'Informations',
    'statistics' => 'Statistiques',
    'participants' => 'Participants',
    'products' => 'Produits',
    'admin_mode' => 'Mode administration',
    'back_to_dashboard' => 'Retour au tableau de bord',
    'share_link' => 'Lien de partage',
    'copy' => 'Copier',
    'send_reminder' => 'Envoyer un rappel',
    'send_pickup_info' => 'Envoyer les infos de récupération',
    'total_amount' => 'Montant total',
    'shipping_fee' => 'Frais de port',
    'current_tier' => 'Palier actuel',
    'next_tier' => 'encore {weight} kg pour le prochain palier',
    'payments' => 'Paiements',
    'received' => 'reçus sur',
    'total_weight' => 'Poids total',
    'available_products' => 'Produits disponibles',
    'no_products_yet' => 'Aucun produit n\'a encore été ajouté à cette commande.',
    'update_order' => 'Mettre à jour ma commande',
    
    // Participant
    'organizer' => 'Organisateur',
    'must_login' => 'Vous devez être connecté pour participer à cette commande.',
    'join_order' => 'Participer à cette commande',
    'my_order' => 'Ma commande',
    'total_to_pay' => 'Total à payer',
    'payment_status' => 'Statut paiement',
    'paid' => 'Payé',
    'unpaid' => 'Non payé',
    'mark_as_paid' => 'Marquer comme payé',
    'mark_as_unpaid' => 'Marquer comme non payé',
    'order_summary' => 'Récapitulatif des commandes',
    'summary_total' => 'TOTAL',
    'grand_total' => 'TOTAL GÉNÉRAL',
    
    // Messages
    'error_occurred' => 'Une erreur est survenue.',
    'order_created' => 'Commande créée avec succès.',
    'order_updated' => 'Votre commande a été mise à jour avec succès.',
    'product_added' => 'Produit ajouté avec succès.',
    'reminder_sent' => 'Rappel envoyé avec succès.',
    'pickup_info_sent' => 'Informations de récupération envoyées avec succès.',
    'payment_updated' => 'Statut de paiement mis à jour.',
    'joined_order' => 'Vous avez rejoint la commande avec succès.',
    'account_created' => 'Votre compte a été créé avec succès.',
    'logged_out' => 'Vous avez été déconnecté.',
    'login_success' => 'Connexion réussie.',
    'must_login_to_join' => 'Vous devez être connecté pour participer à cette commande.',
    'order_closed' => 'Cette commande est fermée. Vous ne pouvez plus la modifier.',
    
    // Validation
    'required_field' => 'Ce champ est requis.',
    'invalid_email' => 'L\'email n\'est pas valide.',
    'email_exists' => 'Cet email est déjà utilisé.',
    'min_8_chars' => '8 caractères minimum.',
    'passwords_not_match' => 'Les mots de passe ne correspondent pas.',
    'invalid_date' => 'Format de date invalide.',
    'future_date' => 'La date doit être ultérieure à maintenant.',
    'pickup_after_deadline' => 'La date de récupération doit être ultérieure à la date limite.',
    'at_least_one_tier' => 'Au moins un palier de frais est requis.',
    'invalid_url' => 'L\'URL du produit n\'est pas valide.',
    'at_least_one_variation' => 'Au moins une variation valide est requise.',
    'wrong_credentials' => 'Email ou mot de passe incorrect.',
];
?>