<?php
// Fichier de traduction français
$translations = [
    // Navigation
    'home' => 'Accueil',
    'dashboard' => 'Tableau de bord',
    'create_order' => 'Créer une commande',
    'administration' => 'Administration',
    'help' => 'Aide',
    'help_description' => 'Guide d\'utilisation et aide pour utiliser l\'application',
    'help_welcome_message' => 'Bienvenue dans la section d\'aide. Vous trouverez ici toutes les informations nécessaires pour utiliser efficacement l\'application.',
    'login' => 'Connexion', 
    'register' => 'Inscription',
    'logout' => 'Déconnexion',
    
    // Pages générales
    'welcome' => 'Bienvenue sur',
    'welcome_text' => 'La solution simple pour organiser vos commandes groupées.',
    'welcome_detail' => 'Créez facilement des commandes groupées, invitez vos amis, et optimisez les frais de livraison.',
    'please_login' => 'Inscrivez-vous ou connectez-vous pour commencer.',
    'register_now' => 'S\'inscrire',
    'login_now' => 'Se connecter',
    'create_order_now' => 'Créer une commande',
    'my_dashboard' => 'Mon tableau de bord',
    
    // Sections accueil
    'create_orders' => 'Créez des commandes',
    'create_orders_text' => 'Définissez les produits disponibles, les dates limites et les conditions de récupération.',
    'share_with_friends' => 'Partagez avec vos amis',
    'share_with_friends_text' => 'Invitez facilement des participants grâce à un lien unique pour chaque commande.',
    'save_on_fees' => 'Économisez sur les frais',
    'save_on_fees_text' => 'Réduisez les frais de port grâce aux commandes groupées et répartissez-les équitablement.',
    'how_it_works' => 'Comment ça marche ?',
    'step1' => 'Créez une commande',
    'step1_text' => 'Définissez les produits, les dates et les frais de port.',
    'step2' => 'Invitez des participants',
    'step2_text' => 'Partagez le lien unique de votre commande.',
    'step3' => 'Suivez les commandes',
    'step3_text' => 'Gérez les participants et leurs paiements.',
    'step4' => 'Organisez la distribution',
    'step4_text' => 'Récupérez les commandes et distribuez-les.',
    
    // Compte utilisateur
    'first_name' => 'Prénom',
    'last_name' => 'Nom',
    'email' => 'Email',
    'phone' => 'Téléphone',
    'phone_placeholder' => '06 12 34 56 78',
    'phone_help' => 'Facultatif - utile pour vous contacter le jour de la distribution',
    'password' => 'Mot de passe',
    'confirm_password' => 'Confirmation du mot de passe',
    'already_registered' => 'Déjà inscrit ?',
    'not_registered' => 'Pas encore de compte ?',
    'sign_up' => 'S\'inscrire',
    
    // Tableaux de bord
    'orders_created' => 'Commandes créées',
    'orders_joined' => 'Commandes participées',
    'orders_completed' => 'Commandes terminées',
    'my_created_orders' => 'Mes commandes créées',
    'my_participations' => 'Mes participations',
    'no_orders_created' => 'Vous n\'avez pas encore créé de commande.',
    'create_one_now' => 'Créez-en une maintenant',
    'no_participations' => 'Vous ne participez à aucune commande pour le moment.',
    'public_orders' => 'Commandes publiques',
    'public_order_description' => 'Commandes ouvertes à tous les utilisateurs',
    'no_participants_joined' => 'Aucun participant n\'a encore rejoint cette commande.',
    'still_need' => 'Il reste',
    'for_next_tier' => 'pour atteindre le palier suivant',
    'import_order' => 'Importer une commande',
    
    // Commande
    'order' => 'Commande',
    'order_title' => 'Titre de la commande',
    'order_type' => 'Type de commande',
    'deadline' => 'Date limite',
    'pickup_date' => 'Date de récupération',
    'pickup_address' => 'Adresse de récupération',
    'weight_based' => 'Basée sur le poids total',
    'quantity_based' => 'Basée sur le nombre de produits',
    'amount_based' => 'Basée sur le coût total',
    'no_shipping' => 'Sans frais de port',
    'tiers' => 'Paliers de frais de port',
    'product_name' => 'Nom du produit',
    'product_url' => 'URL d\'information (facultatif)',
    'product_url_help' => 'Lien vers une page d\'information sur le produit',
    'product_variation' => 'Variation',
    'product_weight' => 'Poids',
    'product_price' => 'Prix',
    'product_quantity' => 'Quantité',
    'add_product' => 'Ajouter un produit',
    'add_variation' => 'Ajouter une variation',
    'variation_name' => 'Nom de la variation',
    'min' => 'Min',
    'max' => 'Max',
    'shipping_cost' => 'Frais (€)',
    'add_tier' => 'Ajouter un palier',
    'shipping_tiers' => 'Paliers de frais de port',
    'no_shipping_tiers' => 'Aucun palier défini',
    'create_order_btn' => 'Créer la commande',
    'cancel' => 'Annuler',
    'add' => 'Ajouter',
    'remove' => 'Supprimer',
    'more_info' => 'Plus d\'informations',
    
    // État des commandes
    'open' => 'Ouverte',
    'closed' => 'Fermée',
    'created_on' => 'Créée le',
    'manage' => 'Gérer',
    'view' => 'Voir',
    'view_edit' => 'Voir / Modifier',
    
    // Gestion commande admin
    'information' => 'Informations',
    'statistics' => 'Statistiques',
    'participants' => 'Participants',
    'products' => 'Produits',
    'admin_mode' => 'Mode administration',
    'back_to_dashboard' => 'Retour au tableau de bord',
    'share_link' => 'Lien de partage',
    'copy' => 'Copier',
    'send_reminder' => 'Envoyer un rappel',
    'send_pickup_info' => 'Envoyer les infos de récupération',
    'total_amount' => 'Montant total',
    'shipping_fee' => 'Frais de port',
    'current_tier' => 'Palier actuel',
    'next_tier' => 'encore {weight} kg pour le prochain palier',
    'payments' => 'Paiements',
    'received' => 'reçus sur',
    'total_weight' => 'Poids total',
    'available_products' => 'Produits disponibles',
    'no_products_yet' => 'Aucun produit n\'a encore été ajouté à cette commande.',
    'update_order' => 'Mettre à jour ma commande',
    
    // Participant
    'organizer' => 'Organisateur',
    'must_login' => 'Vous devez être connecté pour participer à cette commande.',
    'join_order' => 'Participer à cette commande',
    'leave_order' => 'Quitter cette commande',
    'my_order' => 'Ma commande',
    'total_to_pay' => 'Total à payer',
    'payment_status' => 'Statut paiement',
    'paid' => 'Payé',
    'unpaid' => 'Non payé',
    'mark_as_paid' => 'Marquer comme payé',
    'mark_as_unpaid' => 'Marquer comme non payé',
    'order_summary' => 'Récapitulatif des commandes',
    'summary_total' => 'TOTAL',
    'grand_total' => 'TOTAL GÉNÉRAL',
    
    // Messages
    'error_occurred' => 'Une erreur est survenue.',
    'order_created' => 'Commande créée avec succès.',
    'order_updated' => 'Votre commande a été mise à jour avec succès.',
    'product_added' => 'Produit ajouté avec succès.',
    'reminder_sent' => 'Rappel envoyé avec succès.',
    'pickup_info_sent' => 'Informations de récupération envoyées avec succès.',
    'payment_updated' => 'Statut de paiement mis à jour.',
    'joined_order' => 'Vous avez rejoint la commande avec succès.',
    'left_order' => 'Vous avez quitté la commande avec succès.',
    'confirm_leave_order' => 'Êtes-vous sûr de vouloir quitter cette commande ? Tous vos produits commandés seront supprimés.',
    'account_created' => 'Votre compte a été créé avec succès.',
    'logged_out' => 'Vous avez été déconnecté.',
    'login_success' => 'Connexion réussie.',
    'must_login_to_join' => 'Vous devez être connecté pour participer à cette commande.',
    'order_closed' => 'Cette commande est fermée. Vous ne pouvez plus la modifier.',
    'turnstile_failed' => 'Vérification anti-robot échouée. Veuillez réessayer.',
    
    // Validation
    'required_field' => 'Ce champ est requis.',
    'invalid_email' => 'L\'email n\'est pas valide.',
    'email_exists' => 'Cet email est déjà utilisé.',
    'min_8_chars' => '8 caractères minimum.',
    'passwords_not_match' => 'Les mots de passe ne correspondent pas.',
    'invalid_date' => 'Format de date invalide.',
    'future_date' => 'La date doit être ultérieure à maintenant.',
    'pickup_after_deadline' => 'La date de récupération doit être ultérieure à la date limite.',
    'at_least_one_tier' => 'Au moins un palier de frais est requis.',
    'invalid_url' => 'L\'URL du produit n\'est pas valide.',
    'at_least_one_variation' => 'Au moins une variation valide est requise.',
    'wrong_credentials' => 'Email ou mot de passe incorrect.',
    'invalid_order_type' => 'Le type de commande est invalide.',
    
    // Nouvelles clés pour commande.php
    'missing_order_id' => 'ID de commande manquant.',
    'order_not_found' => 'Commande introuvable.',
    'administrator' => 'Administrateur',
    'description' => 'Description',
    'product' => 'Produit',
    'weight' => 'Poids',
    'price' => 'Prix',
    'quantity' => 'Quantité',
    'info' => 'Info',
    'update_my_order' => 'Mettre à jour ma commande',
    'variation' => 'Variation',
    'amount' => 'Montant',
    'total' => 'TOTAL',
    'shipping_fees' => 'Frais de port',
    'no_products_added' => 'Aucun produit n\'a encore été ajouté à cette commande.',
    
    // Nouvelles clés pour import_commande.php
    'must_login_to_import' => 'Vous devez être connecté pour importer une commande.',
    'file_upload_error' => 'Erreur lors de l\'upload du fichier.',
    'file_read_error' => 'Impossible de lire le contenu du fichier.',
    'order_imported' => 'Commande importée avec succès.',
    'import_from_file' => 'Importer depuis un fichier',
    'import' => 'Importer',
    'import_from_text' => 'Importer depuis un texte',
    
    // Page admin_commande
    'manage_order' => 'Gestion de commande',
    'view_order' => 'Voir la commande',
    'back_to_dashboard' => 'Retour au tableau de bord',
    'information' => 'Informations',
    'deadline' => 'Date limite',
    'modify' => 'Modifier',
    'pickup' => 'Récupération',
    'order_type' => 'Type de commande',
    'weight_based' => 'Basée sur le poids total',
    'quantity_based' => 'Basée sur le nombre de produits',
    'amount_based' => 'Basée sur le coût total',
    'no_shipping' => 'Sans frais de port',
    'share_link' => 'Lien de partage',
    'copy' => 'Copier',
    'description' => 'Description',
    'add' => 'Ajouter',
    'visibility' => 'Visibilité',
    'make_private' => 'Rendre privée',
    'make_public' => 'Rendre publique',
    'public_order_info' => 'Cette commande est visible par tous les utilisateurs sur le tableau de bord.',
    'private_order_info' => 'Cette commande n\'est visible que par les participants.',
    'send_reminder' => 'Envoyer un rappel',
    'send_pickup_info' => 'Envoyer les infos de récupération',
    'export_pdf' => 'Exporter en PDF',
    'export_checklist' => 'Exporter la liste de contrôle',
    'checklist_pdf' => 'Liste de contrôle PDF',
    'participants_products' => 'Participants et Produits',
    'summary_controls' => 'Récapitulatif et Contrôles',
    'payment_received' => 'Paiement reçu',
    'products_ordered' => 'Produits commandés',
    'all_participants_contacted' => 'Tous les participants ont été contactés',
    'all_payments_received' => 'Tous les paiements ont été reçus',
    'order_placed_supplier' => 'Commande passée chez le fournisseur',
    'products_collected_supplier' => 'Produits récupérés chez le fournisseur',
    'all_products_collected' => 'Tous les participants ont récupéré leurs produits',
    'notes' => 'Notes',
    
    // Profil utilisateur
    'profile' => 'Mon profil',
    'personal_information' => 'Informations personnelles',
    'account_information' => 'Informations du compte',
    'save_changes' => 'Sauvegarder les modifications',
    'change_password' => 'Changer le mot de passe',
    'current_password' => 'Mot de passe actuel',
    'new_password' => 'Nouveau mot de passe',
    'current_password_required' => 'Le mot de passe actuel est requis',
    'current_password_incorrect' => 'Le mot de passe actuel est incorrect',
    'password_changed' => 'Mot de passe modifié avec succès',
    'profile_updated' => 'Profil mis à jour avec succès',
    'member_since' => 'Membre depuis',
    'last_update' => 'Dernière mise à jour',
    'back_to_dashboard' => 'Retour au tableau de bord',
    'duplicate' => 'Dupliquer',
    'statistics' => 'Statistiques',
    'participants' => 'Participants',
    'products' => 'Produits',
    'total_amount' => 'Montant total',
    'shipping_cost' => 'Frais de port',
    'total_weight' => 'Poids total',
    'current_tier' => 'Palier actuel',
    'next_tier_info' => 'encore {weight} kg pour le prochain palier',
    'payments' => 'Paiements',
    'received' => 'reçus sur',
    'add_product' => 'Ajouter un produit',
    'no_products' => 'Aucun produit n\'a été ajouté à cette commande.',
    'product_info' => 'Info',
    'delete_product_confirm' => 'Êtes-vous sûr de vouloir supprimer ce produit ?',
    'variation' => 'Variation',
    'weight' => 'Poids',
    'price' => 'Prix',
    'actions' => 'Actions',
    'delete_variation_confirm' => 'Êtes-vous sûr de vouloir supprimer cette variation ?',
    'no_participants' => 'Aucun participant n\'a rejoint cette commande.',
    'participant' => 'Participant',
    'product_amount' => 'Montant produits',
    'shipping_share' => 'Frais de port',
    'total' => 'Total',
    'payment_status' => 'Statut paiement',
    'paid' => 'Payé',
    'unpaid' => 'Non payé',
    'mark_as_paid' => 'Marquer comme payé',
    'mark_as_unpaid' => 'Marquer comme non payé',
    'product_name' => 'Nom du produit',
    'product_url' => 'URL d\'information (facultatif)',
    'product_url_help' => 'Lien vers une page d\'information sur le produit',
    'variations' => 'Variations',
    'variation_name' => 'Nom de la variation',
    'product_weight' => 'Poids (kg)',
    'product_price' => 'Prix (€)',
    'remove' => 'Supprimer',
    'add_variation' => 'Ajouter une variation',
    'cancel' => 'Annuler',
    'update_dates' => 'Modifier les dates',
    'deadline_help' => 'Date limite pour passer commande',
    'pickup_date' => 'Date de récupération',
    'pickup_help' => 'Date de récupération des produits',
    'update' => 'Mettre à jour',
    'order_description' => 'Description de la commande',
    'order_description_placeholder' => 'Décrivez votre commande groupée, les conditions spéciales, etc.',
    'order_description_help' => 'Cette description sera visible par tous les participants de la commande.',
    'description_help' => 'Informations supplémentaires sur la commande',
    'save' => 'Enregistrer',
    'link_copied' => 'Lien copié dans le presse-papier !',
    'no_products_participant' => 'Aucun produit',
    'created_on' => 'Créée le',
    'organizer' => 'Organisateur',
    
    // Nouvelles clés
    'product_info_url' => 'URL d\'information (facultatif)',
    'product_info_url_description' => 'Lien vers une page d\'information sur le produit',
    'based_on_weight' => 'Basée sur le poids total',
    'based_on_quantity' => 'Basée sur le nombre de produits',
    'based_on_amount' => 'Basée sur le montant total',
    'based_on_no_shipping' => 'Sans frais de port',
    'private_order_description' => 'Cette commande n\'est visible que par les participants',
    'send_pickup' => 'Envoyer les infos de récupération',
    'duplicate_order' => 'Dupliquer la commande',
    'paid_amount' => 'Montant reçu',
    'received_from' => 'sur un total de',
    'order_deleted_successfully' => 'Commande supprimée avec succès',
    'error_deleting_order' => 'Erreur lors de la suppression de la commande',
    'pdf_generated_successfully' => 'PDF généré avec succès',
    'error_generating_pdf' => 'Erreur lors de la génération du PDF',
    'tcpdf_not_available' => 'TCPDF n\'est pas installé. L\'export PDF n\'est pas disponible.',
    
    // Export/Import JSON
    'export_json' => 'Exporter JSON',
    'import_order' => 'Importer une commande',
    'import_json_file' => 'Importer un fichier JSON',
    'select_json_file' => 'Sélectionner un fichier JSON',
    'json_file_format_info' => 'Format accepté: fichiers .json exportés depuis Groupon',
    'import_file' => 'Importer le fichier',
    'import_info' => 'Informations sur l\'import',
    'supported_format' => 'Format supporté',
    'json_format_description' => 'Seuls les fichiers JSON exportés depuis Groupon sont acceptés.',
    'import_notes' => 'Notes importantes',
    'import_note_1' => 'Un nouvel ID sera généré pour la commande',
    'import_note_2' => 'Seuls les participants existants seront importés',
    'import_note_3' => 'Vous deviendrez l\'administrateur de la commande importée',
    'create_new_order' => 'Créer une nouvelle commande',
    'import_success' => 'Commande importée avec succès !',
    'import_error' => 'Erreur lors de l\'import de la commande',
    'import_error_read_file' => 'Erreur lors de la lecture du fichier',
    'import_error_upload' => 'Erreur lors de l\'upload du fichier',
    'view_order' => 'Voir la commande',
    
    // Nouvelles clés manquantes
    'delete' => 'Supprimer',
    'cost_based' => 'Basée sur le coût total',
    'are_you_sure_delete_product' => 'Êtes-vous sûr de vouloir supprimer ce produit ?',
    'are_you_sure_delete_variation' => 'Êtes-vous sûr de vouloir supprimer cette variation ?',
    'modify_dates' => 'Modifier les dates',
    'deadline_description' => 'Date limite pour passer commande',
    'pickup_description' => 'Date de récupération des produits',
];
?>